### ISSUE TITLE
Shortcode to show specific FAQ categories

### ISSUE THREAD

**Issue by websnail** [j-gardner/arconix-faq#32]
Not sure if this is already available but it would be useful to be able to use shortcodes to display specific categories / sub-categories of FAQ rather than the whole thing.
eg: [faq catid=5]

So for example a store shipping policy page could include the primary document information with the FAQ section specific to shipping.

Would also have utility for someone who wants to create FAQ's but break up their FAQ page with a little intro to each section... 

eg: 
The shipping FAQ will provide you with some common questions we get about postage, tracking or how we deal with items lost in the post.
[faq catid=5]

**Comment by j-gardner** [comment]
Hi websnail,

Sorry for the delay. This is available already by using the `group` param of the FAQ. If your FAQ Group was called shipping, your shortcode would look like so:
```
[faq group=shipping]
```

**Comment by websnail** [comment]
Thanks for the reply... Quick follow up.

If the group has a space or other non-standard character how do you codify the group label or are groups sanity checked so that spaces, etc... are not allowed?

Thanks again..

**Comment by j-gardner** [comment]
The group param users the slug of the group.  If the group were called
Shipping and Receiving the slug would be shipping-and-receiving. If you
ruin into issues getting the slug, go to the group editor in the admin and
the slug for each group is there
